services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
        - CFTC_API_KEY=${CFTC_API_KEY:-}
        - CFTC_SECRET=${CFTC_SECRET:-}
      restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
