spring.application.name=macro-dashboard
server.port=8081

cftc.api.url=https://publicreporting.cftc.gov/resource/jun7-fc8e.json
interest.rates.url=https://stats.bis.org/api/v1/data/WS_CBPOL/M.US+XM+GB+JP+AU+CA+CH+NZ/all?lastNObservations=1
finnhub.api.url=https://finnhub.io/api/v1/calendar/economic
finnhub.api.key=d7mcjv1r01qngrvnoargd7mcjv1r01qngrvnoas0
